-- depends_on: {{ ref('stg_csv_archive_log') }}

{{ config(
    materialized='incremental',
    unique_key=['file', 'DUID', 'SETTLEMENTDATE','INTERVENTION'],
    incremental_strategy='delete+insert',
    pre_hook="SET VARIABLE scada_daily_paths = (SELECT COALESCE(NULLIF(list(file), []), ['']) FROM glob('{{ get_csv_archive_path() }}/daily/*.gz'))"
) }}

{%- set check_files_query -%}
SELECT COUNT(*) as cnt FROM glob('{{ get_csv_archive_path() }}/daily/*.gz')
{%- endset -%}

{%- set files_result = run_query(check_files_query) -%}
{%- set has_files = files_result and files_result.rows[0][0] > 0 -%}

{% if has_files %}
WITH scada_staging AS (
  SELECT *
  FROM read_csv(
    getvariable('scada_daily_paths'),
    skip = 1,
    header = 0,
    all_varchar = 1,
    columns = {
      'I': 'VARCHAR',
      'UNIT': 'VARCHAR',
      'XX': 'VARCHAR',
      'VERSION': 'VARCHAR',
      'SETTLEMENTDATE': 'VARCHAR',
      'RUNNO': 'VARCHAR',
      'DUID': 'VARCHAR',
      'INTERVENTION': 'VARCHAR',
      'DISPATCHMODE': 'VARCHAR',
      'AGCSTATUS': 'VARCHAR',
      'INITIALMW': 'VARCHAR',
      'TOTALCLEARED': 'VARCHAR',
      'RAMPDOWNRATE': 'VARCHAR',
      'RAMPUPRATE': 'VARCHAR',
      'LOWER5MIN': 'VARCHAR',
      'LOWER60SEC': 'VARCHAR',
      'LOWER6SEC': 'VARCHAR',
      'RAISE5MIN': 'VARCHAR',
      'RAISE60SEC': 'VARCHAR',
      'RAISE6SEC': 'VARCHAR',
      'MARGINAL5MINVALUE': 'VARCHAR',
      'MARGINAL60SECVALUE': 'VARCHAR',
      'MARGINAL6SECVALUE': 'VARCHAR',
      'MARGINALVALUE': 'VARCHAR',
      'VIOLATION5MINDEGREE': 'VARCHAR',
      'VIOLATION60SECDEGREE': 'VARCHAR',
      'VIOLATION6SECDEGREE': 'VARCHAR',
      'VIOLATIONDEGREE': 'VARCHAR',
      'LOWERREG': 'VARCHAR',
      'RAISEREG': 'VARCHAR',
      'AVAILABILITY': 'VARCHAR',
      'RAISE6SECFLAGS': 'VARCHAR',
      'RAISE60SECFLAGS': 'VARCHAR',
      'RAISE5MINFLAGS': 'VARCHAR',
      'RAISEREGFLAGS': 'VARCHAR',
      'LOWER6SECFLAGS': 'VARCHAR',
      'LOWER60SECFLAGS': 'VARCHAR',
      'LOWER5MINFLAGS': 'VARCHAR',
      'LOWERREGFLAGS': 'VARCHAR',
      'RAISEREGAVAILABILITY': 'VARCHAR',
      'RAISEREGENABLEMENTMAX': 'VARCHAR',
      'RAISEREGENABLEMENTMIN': 'VARCHAR',
      'LOWERREGAVAILABILITY': 'VARCHAR',
      'LOWERREGENABLEMENTMAX': 'VARCHAR',
      'LOWERREGENABLEMENTMIN': 'VARCHAR',
      'RAISE6SECACTUALAVAILABILITY': 'VARCHAR',
      'RAISE60SECACTUALAVAILABILITY': 'VARCHAR',
      'RAISE5MINACTUALAVAILABILITY': 'VARCHAR',
      'RAISEREGACTUALAVAILABILITY': 'VARCHAR',
      'LOWER6SECACTUALAVAILABILITY': 'VARCHAR',
      'LOWER60SECACTUALAVAILABILITY': 'VARCHAR',
      'LOWER5MINACTUALAVAILABILITY': 'VARCHAR',
      'LOWERREGACTUALAVAILABILITY': 'VARCHAR'
    },
    filename = 1,
    null_padding = true,
    ignore_errors = 1,
    auto_detect = false,
    hive_partitioning = false
  )
  WHERE I = 'D' AND UNIT = 'DUNIT' AND VERSION = '3'
)

SELECT
  UNIT,
  DUID,
  CAST(VERSION AS DOUBLE) AS VERSION,
  CAST(RUNNO AS DOUBLE) AS RUNNO,
  CAST(INTERVENTION AS DOUBLE) AS INTERVENTION,
  CAST(DISPATCHMODE AS DOUBLE) AS DISPATCHMODE,
  CAST(AGCSTATUS AS DOUBLE) AS AGCSTATUS,
  CAST(INITIALMW AS DOUBLE) AS INITIALMW,
  CAST(TOTALCLEARED AS DOUBLE) AS TOTALCLEARED,
  CAST(RAMPDOWNRATE AS DOUBLE) AS RAMPDOWNRATE,
  CAST(RAMPUPRATE AS DOUBLE) AS RAMPUPRATE,
  CAST(LOWER5MIN AS DOUBLE) AS LOWER5MIN,
  CAST(LOWER60SEC AS DOUBLE) AS LOWER60SEC,
  CAST(LOWER6SEC AS DOUBLE) AS LOWER6SEC,
  CAST(RAISE5MIN AS DOUBLE) AS RAISE5MIN,
  CAST(RAISE60SEC AS DOUBLE) AS RAISE60SEC,
  CAST(RAISE6SEC AS DOUBLE) AS RAISE6SEC,
  CAST(MARGINAL5MINVALUE AS DOUBLE) AS MARGINAL5MINVALUE,
  CAST(MARGINAL60SECVALUE AS DOUBLE) AS MARGINAL60SECVALUE,
  CAST(MARGINAL6SECVALUE AS DOUBLE) AS MARGINAL6SECVALUE,
  CAST(MARGINALVALUE AS DOUBLE) AS MARGINALVALUE,
  CAST(VIOLATION5MINDEGREE AS DOUBLE) AS VIOLATION5MINDEGREE,
  CAST(VIOLATION60SECDEGREE AS DOUBLE) AS VIOLATION60SECDEGREE,
  CAST(VIOLATION6SECDEGREE AS DOUBLE) AS VIOLATION6SECDEGREE,
  CAST(VIOLATIONDEGREE AS DOUBLE) AS VIOLATIONDEGREE,
  CAST(LOWERREG AS DOUBLE) AS LOWERREG,
  CAST(RAISEREG AS DOUBLE) AS RAISEREG,
  CAST(AVAILABILITY AS DOUBLE) AS AVAILABILITY,
  CAST(RAISE6SECFLAGS AS DOUBLE) AS RAISE6SECFLAGS,
  CAST(RAISE60SECFLAGS AS DOUBLE) AS RAISE60SECFLAGS,
  CAST(RAISE5MINFLAGS AS DOUBLE) AS RAISE5MINFLAGS,
  CAST(RAISEREGFLAGS AS DOUBLE) AS RAISEREGFLAGS,
  CAST(LOWER6SECFLAGS AS DOUBLE) AS LOWER6SECFLAGS,
  CAST(LOWER60SECFLAGS AS DOUBLE) AS LOWER60SECFLAGS,
  CAST(LOWER5MINFLAGS AS DOUBLE) AS LOWER5MINFLAGS,
  CAST(LOWERREGFLAGS AS DOUBLE) AS LOWERREGFLAGS,
  CAST(RAISEREGAVAILABILITY AS DOUBLE) AS RAISEREGAVAILABILITY,
  CAST(RAISEREGENABLEMENTMAX AS DOUBLE) AS RAISEREGENABLEMENTMAX,
  CAST(RAISEREGENABLEMENTMIN AS DOUBLE) AS RAISEREGENABLEMENTMIN,
  CAST(LOWERREGAVAILABILITY AS DOUBLE) AS LOWERREGAVAILABILITY,
  CAST(LOWERREGENABLEMENTMAX AS DOUBLE) AS LOWERREGENABLEMENTMAX,
  CAST(LOWERREGENABLEMENTMIN AS DOUBLE) AS LOWERREGENABLEMENTMIN,
  CAST(RAISE6SECACTUALAVAILABILITY AS DOUBLE) AS RAISE6SECACTUALAVAILABILITY,
  CAST(RAISE60SECACTUALAVAILABILITY AS DOUBLE) AS RAISE60SECACTUALAVAILABILITY,
  CAST(RAISE5MINACTUALAVAILABILITY AS DOUBLE) AS RAISE5MINACTUALAVAILABILITY,
  CAST(RAISEREGACTUALAVAILABILITY AS DOUBLE) AS RAISEREGACTUALAVAILABILITY,
  CAST(LOWER6SECACTUALAVAILABILITY AS DOUBLE) AS LOWER6SECACTUALAVAILABILITY,
  CAST(LOWER60SECACTUALAVAILABILITY AS DOUBLE) AS LOWER60SECACTUALAVAILABILITY,
  CAST(LOWER5MINACTUALAVAILABILITY AS DOUBLE) AS LOWER5MINACTUALAVAILABILITY,
  CAST(LOWERREGACTUALAVAILABILITY AS DOUBLE) AS LOWERREGACTUALAVAILABILITY,
  {{ parse_filename('filename') }} AS file,
  CAST(SETTLEMENTDATE AS TIMESTAMP) AS SETTLEMENTDATE,
  CAST(SETTLEMENTDATE AS DATE) AS DATE,
  CAST(YEAR(CAST(SETTLEMENTDATE AS TIMESTAMP)) AS INT) AS YEAR
FROM scada_staging
{% else %}
SELECT * FROM {{ this }} WHERE FALSE
{% endif %}
